# Reminders

In [1]:
import numpy as np
import matplotlib as plt

In [2]:
a = np.zeros ((5,3)) #Oh! Spaces do not matter! 
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
a.shape

(5, 3)

In [5]:
b = np.array([1,2,3])
b #This is a vector

array([1, 2, 3])

In [7]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(c[1,1]) #If I want the first (python first, zero-indexed) raw?
print(c[1,:]) #First column
print(c[:,1]) 
#What if I want the end of the first r?
print(c[1,1:]) #This is fun, we fix the row number and use a slice for the columns -- If you happen to know it 
print(c.shape)
print(c[c.shape[0]-1,:]) #Also gives you last row
print(c[-1,:]) #How you actually do it

5
[4 5 6]
[2 5]
[5 6]
(2, 3)
[4 5 6]
[4 5 6]


In [29]:
#Back to a larger structure 
a = np.zeros((5,3))
a[1,1] = 777 #One particular element 
a[-2:,-2:] = 1 #Bottom right corner, and negative indexing and slicing 
print(a)

print('Spiderman cast a shadow:')
a[2,:] = a[1,:]/7 #Make the human row (python 2nd) 1/7th of the human second (python 1st) row
print(a)

#Make 8th column a sum of the other 2
#1st attempt manually
a[:,0] = a[:,1] + a[:,2]
print('The new truth:\n',a)

#Another, smarter way
a[:,0] = np.sum(a[:,1:],axis=1) #In this case, don't forget to tell you want horizontal squishing
print('Yet another attempt:\n',a)


[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0.   0.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]
Spiderman cast a shadow:
[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0. 111.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]
The new truth:
 [[  0.   0.   0.]
 [777. 777.   0.]
 [111. 111.   0.]
 [  2.   1.   1.]
 [  2.   1.   1.]]
Yet another attempt:
 [[  0.   0.   0.]
 [777. 777.   0.]
 [111. 111.   0.]
 [  2.   1.   1.]
 [  2.   1.   1.]]
